apiVersion: v1
kind: Service
metadata:
    name: "devopstest-dc69"
    labels:
        app: "devopstest-dc69"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devopstest-dc69"